// Vietnamese localization for Clerk components
export const clerkVietnameseLocalization = {
  signIn: {
    start: {
      title: 'Đăng nhập vào AI Tóm tắt',
      subtitle: 'Truy cập vào bộ công cụ AI mạnh mẽ dành cho sinh viên và nhân viên văn phòng Việt Nam. Tóm tắt văn bản, dịch thuật thông minh và nhiều tính năng AI khác.',
      actionText: 'Chưa có tài khoản?',
      actionLink: 'Đăng ký miễn phí ngay',
    },
    password: {
      title: 'Nhập mật khẩu',
      subtitle: 'để tiếp tục đến {{applicationName}}',
      actionLink: 'Sử dụng phương thức khác',
    },
    forgotPassword: {
      title: 'Quên mật khẩu?',
      subtitle: 'Nhập email để nhận liên kết đặt lại mật khẩu',
      formTitle: 'Đặt lại mật khẩu',
      formSubtitle: 'Nhập email đã đăng ký',
      resendButton: 'Gửi lại email',
    },
  },
  signUp: {
    start: {
      title: 'Tạo tài khoản AI Tóm tắt',
      subtitle: 'Tham gia cộng đồng hơn 10,000+ người dùng đang sử dụng AI để tăng năng suất học tập và làm việc. Hoàn toàn miễn phí để bắt đầu!',
      actionText: 'Đã có tài khoản?',
      actionLink: 'Đăng nhập ngay',
    },
    emailLink: {
      title: 'Xác thực email',
      subtitle: 'để hoàn tất tạo tài khoản',
      formTitle: 'Kiểm tra email',
      formSubtitle: 'Chúng tôi đã gửi liên kết xác thực đến {{identifier}}',
      resendButton: 'Gửi lại email',
    },
    emailCode: {
      title: 'Xác thực email',
      subtitle: 'để hoàn tất tạo tài khoản',
      formTitle: 'Nhập mã xác thực',
      formSubtitle: 'Chúng tôi đã gửi mã 6 số đến email của bạn. Vui lòng nhập mã để tiếp tục.',
      resendButton: 'Gửi lại mã',
    },
  },
  userProfile: {
    navbar: {
      title: 'Tài khoản',
      description: 'Quản lý thông tin tài khoản',
    },
    start: {
      headerTitle: 'Tài khoản của tôi',
      profileSection: {
        title: 'Thông tin cá nhân',
      },
      usernameSection: {
        title: 'Tên người dùng',
      },
      emailAddressesSection: {
        title: 'Địa chỉ email',
      },
      connectedAccountsSection: {
        title: 'Tài khoản liên kết',
      },
      passwordSection: {
        title: 'Mật khẩu',
      },
      mfaSection: {
        title: 'Xác thực hai yếu tố',
      },
      dangerSection: {
        title: 'Nguy hiểm',
        deleteAccountButton: 'Xóa tài khoản',
      },
    },
  },
  userButton: {
    action__manageAccount: 'Quản lý tài khoản',
    action__signOut: 'Đăng xuất',
    action__signOutAll: 'Đăng xuất tất cả',
  },
  organizationProfile: {
    navbar: {
      title: 'Tổ chức',
      description: 'Quản lý tổ chức',
    },
  },
  formFieldLabel__emailAddress: 'Địa chỉ email',
  formFieldLabel__emailAddresses: 'Địa chỉ email',
  formFieldLabel__phoneNumber: 'Số điện thoại',
  formFieldLabel__username: 'Tên người dùng',
  formFieldLabel__emailAddress_username: 'Email hoặc tên người dùng',
  formFieldLabel__password: 'Mật khẩu',
  formFieldLabel__currentPassword: 'Mật khẩu hiện tại',
  formFieldLabel__newPassword: 'Mật khẩu mới',
  formFieldLabel__confirmPassword: 'Xác nhận mật khẩu',
  formFieldLabel__firstName: 'Tên',
  formFieldLabel__lastName: 'Họ',
  formFieldInputPlaceholder__emailAddress: 'john@example.com',
  formFieldInputPlaceholder__emailAddresses: 'Nhập hoặc dán một hoặc nhiều địa chỉ email, cách nhau bằng dấu cách hoặc dấu phẩy',
  formFieldInputPlaceholder__phoneNumber: '',
  formFieldInputPlaceholder__username: 'tên_người_dùng',
  formFieldInputPlaceholder__emailAddress_username: '',
  formFieldInputPlaceholder__password: '',
  formFieldInputPlaceholder__firstName: 'John',
  formFieldInputPlaceholder__lastName: 'Doe',
  formFieldAction__forgotPassword: 'Quên mật khẩu?',
  formFieldHintText__optional: 'Tùy chọn',
  formButtonPrimary: 'Tiếp tục',
  signInEnterPasswordTitle: 'Nhập mật khẩu của bạn',
  backButton: 'Quay lại',
  footerActionLink__useAnotherMethod: 'Sử dụng phương thức khác',
  badge__primary: 'Chính',
  badge__thisDevice: 'Thiết bị này',
  badge__userDevice: 'Thiết bị người dùng',
  badge__otherImpersonatorDevice: 'Thiết bị mạo danh khác',
  badge__default: 'Mặc định',
  badge__unverified: 'Chưa xác thực',
  badge__requiresAction: 'Cần hành động',
  badge__you: 'Bạn',
  footerPageLink__help: 'Trợ giúp',
  footerPageLink__privacy: 'Quyền riêng tư',
  footerPageLink__terms: 'Điều khoản',
  paginationButton__previous: 'Trước',
  paginationButton__next: 'Tiếp',
  paginationRowText__displaying: 'Hiển thị',
  paginationRowText__of: 'của',
  membershipRole__admin: 'Quản trị viên',
  membershipRole__basicMember: 'Thành viên',
  membershipRole__guestMember: 'Khách',
  signUp__begin: {
    title: 'Tạo tài khoản',
    subtitle: 'để tiếp tục đến {{applicationName}}',
    actionText: 'Đã có tài khoản?',
    actionLink: 'Đăng nhập',
  },
  signIn__begin: {
    title: 'Đăng nhập',
    subtitle: 'để tiếp tục đến {{applicationName}}',
    actionText: 'Chưa có tài khoản?',
    actionLink: 'Đăng ký',
  },
  socialButtonsBlockButton: 'Tiếp tục với {{provider|titleize}}',
  dividerText: 'hoặc',
  formFieldError__notMatchingPasswords: 'Mật khẩu không khớp.',
  formFieldError__matchingPasswords: 'Mật khẩu khớp.',
  formFieldError__verificationLinkExpired: 'Liên kết xác thực đã hết hạn. Vui lòng yêu cầu liên kết mới.',
  formFieldError__verificationCodeExpired: 'Mã xác thực đã hết hạn. Vui lòng yêu cầu mã mới.',
  formFieldError__verificationCodeIncorrect: 'Mã xác thực không chính xác.',
  formFieldHintText__password: 'Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường và số.',
  formFieldHintText__confirmPassword: 'Nhập lại mật khẩu để xác nhận.',
  formFieldAction__resendCode: 'Gửi lại mã',
  formFieldAction__resendLink: 'Gửi lại liên kết',
  genericError__somethingWentWrong: 'Đã xảy ra lỗi. Vui lòng thử lại.',
};